package manager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import manager.swing.MainFrame;
import sql_data.Query1;

import javax.swing.*;
import javax.swing.text.BadLocationException;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.time.LocalDate;

/**
 *
 * @author Daniel
 */
public class NewJFrame extends javax.swing.JFrame {
    public static String img;
  //  public static String printare;


    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() throws BadLocationException {
super("Previzualizare - Apăsați P pentru printare la imprimantă sau pdf");
img ="";
    initComponents();
 if (MainFrame.fisa=="editare"){   setLocation(200,75);}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() throws BadLocationException {





        jPanel1 = new javax.swing.JPanel();

        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelantet = new javax.swing.JLabel("");
        jLabel2 = new javax.swing.JLabel("                             ");
        jLabel3 = new javax.swing.JLabel("");
        jLabel4 = new javax.swing.JLabel(" ");
        jLabel5 = new javax.swing.JLabel("");
        jLabel6 = new javax.swing.JLabel("");
        jLabel7 = new javax.swing.JLabel("");
        jLabel9 = new javax.swing.JLabel("");
        jLabel8 = new javax.swing.JLabel("");
        jButton1 = new javax.swing.JButton("Printează Fișa Personală");
        jButton2 = new javax.swing.JButton("Printează");
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTextPane1.setFocusable(false);
        afisare_item.initiere1_jnewframe();
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);



        jLabel2.setFont(new Font("Serif", Font.PLAIN, 16));
        jLabel4.setFont(new Font("Serif", Font.PLAIN, 16));
        jLabel5.setFont(new Font("Serif", Font.PLAIN, 16));


        ImageIcon icon = new ImageIcon(MainFrame.reverse1);

        int h=0; int w=0;
try {
     h = icon.getIconHeight();
     w = icon.getIconWidth();
} catch(Exception e){}

        Image scaleImage = icon.getImage().getScaledInstance(w, h,Image.SCALE_DEFAULT);
        jLabel1.setIcon(new javax.swing.ImageIcon(scaleImage)); // NOI18N

     //   jLabel1.setText("jLabel1");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(0, 102, 102), null, new java.awt.Color(153, 153, 153)));

        jTextPane1.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jTextPane1);

       // Container cp = getContentPane();


if (MainFrame.fisa=="editare") {

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(102, 102, 102)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );










        pack();
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

 printare1();
                printare.printComponenet(jPanel1);
        }
           public void printare1() {
               MainFrame.fisa="printare";

new Thread(new FrameRunnable()).start();
            NewJFrame n = (NewJFrame) new JFrame();
            n.setVisible(true);

            }




    //   jLabel1.setText("jLabel1");


});}

 if (MainFrame.fisa=="printare"){
                jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(0, 102, 102), null, new java.awt.Color(153, 153, 153)));

                jTextPane1.setBackground(new java.awt.Color(204, 204, 204));
                jScrollPane1.setViewportView(jTextPane1);

jPanel1.removeAll();
jLabel1.removeAll();


               // ImageIcon icon = new ImageIcon(Home_search.reverse1);
             //   int h  = icon.getIconHeight();
            //    int w  = icon.getIconWidth();
                System.out.println("h si w subnt: "+h+" "+w);
                h= (int) (h*0.5);
                w= (int) (w*0.5);
              if (h==0){Image scaleImage1 = icon.getImage().getScaledInstance(Image.SCALE_DEFAULT, Image.SCALE_DEFAULT,Image.SCALE_DEFAULT);  jLabel3.setIcon(new javax.swing.ImageIcon(scaleImage1));}else
              {Image scaleImage1 = icon.getImage().getScaledInstance(w, h,Image.SCALE_DEFAULT);  jLabel3.setIcon(new javax.swing.ImageIcon(scaleImage1));}


jScrollPane1.setBorder(null);

jPanel1.setBackground(Color.white);

        LocalDate today = LocalDate.now();
      String t = ""+today;
        String actual = ConversUserData.con_home_search1(t);
Query1.cauta_nume_biserica("biserica");
                jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jLabelantet.setBackground(new java.awt.Color(19, 74, 122));
                jLabelantet.setText("<html><font color='#726E6D' Size=2><b><LEFT>" + Query1.Biserica[1]+"<br>"+
                        Query1.adresa_biserica[1]+"     Tel.:" +Query1.tel_biserica[1]+"<br>" +
                        "Astăzi:"+actual+" ______</left>");
                jLabel9.setText("<html><font color='#726E6D' Size=5><b> Fișă Personală</b></font></html>");



        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabelantet, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(221, 221, 221))
                                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(0, 10, Short.MAX_VALUE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGap(108, 108, 108))))))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelantet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabelantet.getAccessibleContext().setAccessibleName("jLabelantet");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();




        addKeyListener
                (new KeyAdapter() {
                    public void keyPressed(KeyEvent e) {

                        int key = e.getKeyCode();
                        if (key == KeyEvent.VK_P) {
                            printare.printComponenet(jPanel1);

                        }}});



        if (MainFrame.fisa=="printare"){

                setLocation(420,0);
setSize(585,775);}

     if (MainFrame.fisa=="editare"){

         setLocation(420,0);
         setSize(585,775);}





 }}

//        });
    // </editor-fold>














    public class FrameRunnable implements  Runnable{

        public void run(){

            NewJFrame n;
            try {
                n = new NewJFrame();
                n.show();
            } catch (BadLocationException e) {
                e.printStackTrace();
            }



        }

    }


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NewJFrame().setVisible(true);

                } catch (BadLocationException e) {
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify
    public static javax.swing.JLabel jLabel1,jLabel2,jLabel3,jLabel4,jLabel5,jLabel6,jLabel7,jLabel8, jLabel9, jLabel10, jLabel11, jLabelantet;
    public static javax.swing.JPanel jPanel1,jPanel2;
    public static javax.swing.JButton jButton1,jButton2 ;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextPane jTextPane1;
    public static String nume, tel, data_nastere, data_casatorie, data_botez, altele;
    // End of variables declaration
}
